events/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin 
import views

urlpatterns = patterns('',
	# ex: /events/
	url(r'^$', views.list_events, name='list_events'),
)

tehba/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings 
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import views 

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tehraner.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.home, name='home'),

    url(r'^events/', include('events.urls', namespace="events")),

    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
	# static files (images, css, javascript, etc.)
	# this is used when we are on local computer. 
	# when we go to production, the web server configuration would
	# serve static media (DEBUG = False)

	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', 
			{
				'document_root': settings.MEDIA_ROOT
			})
	)

	urlpatterns += staticfiles_urlpatterns()

events/models.py
import datetime
from django.db import models
from django.utils import timezone 
# Create your models here
# if is_reliable == True, the admin-user himself should make 
# 'on' to be False
class Event(models.Model):
	SMALL_SIZE  = 1
	HALF_SIZE   = 2
	WIDE_SIZE   = 3
	SQUARE_SIZE = 4

	sizes = (
 		(SMALL_SIZE, 'small'),
 		(HALF_SIZE, 'half'),
 		(WIDE_SIZE, 'wide'),
 		(SQUARE_SIZE, 'square'),
	)

	name             = models.CharField(max_length=60)
	description      = models.TextField(max_length=550)
	size             = models.IntegerField(max_length=6, choices=sizes, default=SQUARE_SIZE)
	image            = models.ImageField(upload_to='images/', max_length=1000, null=True, blank=True)

	order            = models.IntegerField(default=-10)
	on               = models.BooleanField(default=False)

	expiration_date = models.DateTimeField('expires on')
	publish_date     = models.DateTimeField('date published', default=datetime.datetime.now() )


	def __unicode__(self):
		return self.name 

	def is_reliable(self):
		return self.expiration_date > timezone.now()
	is_reliable.boolean = True
	is_reliable.short_description = 'still active?'

#todo:
#

events/views.py
from django.shortcuts import render
from events.models import Event 

# Create your views here.
def list_events(request):
	latest_event_list = Event.objects.filter(on=True).order_by('order')[:10]
	context = {'today_events': latest_event_list}
	return render(request, 'events/index.html', context)

tehba/views.py
from django.http import HttpResponse

def home(request):
	return HttpResponse('hello people')

events/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		{% block in_head %}

		{% endblock %}
	</head>

	<body>
		<a href="http://localhost:8000/admin">admin</a>
		{% block content %}

		{% endblock %}
	</body>
</html>

events/templates/events/index.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block in_head %}
<link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}" />
{% endblock%}


{% block content %}
	<div id="whole" class="center">
		<div id="right">
			<div id="logo"></div>
		</div>
		<div id="left">
			{% if today_events %} 
				{% for event in today_events %} 
					<div class="{{ event.get_size_display }}">
						<h1>{{ event.name }}</h1>
						{% if event.image %}
							<img src="{{ event.image.url }}">
						{% endif %}
						<p>{{ event.description }}</p>
					</div>					
				{% endfor %}
			{% else %}
				<p>No events are available</p>
			{% endif %}
		</div>
	</div>
{% endblock %}